import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import MainNavbar from "$/components/UI/Headers/MainNavbar";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: {
	children: React.ReactNode;
}) {
	return (
		<html lang="en">
			<body className={`bg-[#F2F0E6]  ${inter.className}`}>
				<MainNavbar />
				<div className=" mt-10">{children}</div>
			</body>
		</html>
	);
}

